### ISSUE TITLE
Frame temperature sensor

### ISSUE THREAD

**Issue by Hr46ph** [JiMcNulty/FDC#1]
Hi There!

So you say:

```
X gantry on the opposite side of the X endstop at the end, touching the aluminum
    I know, it's a pain to find a way to install it, but it's the only place to put the sensor that will give accurate results
    Other places are a gamble, try it if you want - if it works, great, if it doesn't, you know why
```
Don't mind me asking but can you explain why that particular spot is the only place that gives accurate results?

I'm trying to think why the Y gantry extrusion, say somewhere in the middle, isn't just as good a spot or even better?

Thanks!

**Comment by JiMcNulty** [comment]
> Hi There!
> 
> So you say:
> 
> ```
> X gantry on the opposite side of the X endstop at the end, touching the aluminum
>     I know, it's a pain to find a way to install it, but it's the only place to put the sensor that will give accurate results
>     Other places are a gamble, try it if you want - if it works, great, if it doesn't, you know why
> ```
> 
> Don't mind me asking but can you explain why that particular spot is the only place that gives accurate results?
> 
> I'm trying to think why the Y gantry extrusion, say somewhere in the middle, isn't just as good a spot or even better?
> 
> Thanks!

Sure,

X tube is the one that absorb the most heat because it is directly above the bed, the sensor can be anywhere you want it on X, but the side is the easiest place.

Because the more heat the tube gets the more it deforms, we want to know the temp of this specific tube.
Putting it on Y would have worked if X and Y can be thermally coupled, but because they are attached with joiners thy don't conduct heat to each other, so we are left with the sensor on X

**Comment by Hr46ph** [comment]
Oke, that makes sense. When I create a bed mesh cold, during heating and after heat soaked, it seems to me (but I could be wrong ofc) that the bowing of X and Y are very similar. I have vcore 300 in an enclosure. I'll test it to make sure.

The issue I see is that I dont have dragchains, just an umbilical from the printhead. I don't quite see how I can attach a probe to the gantry when its moving back and forth, unless I guide it somehow.

**Comment by Hr46ph** [comment]
When I grabbed a thermistor I found I had several so I installed 2. One on the Y extrusion, somewhere in the middle of it, and the other in the gantry, also in the middle.

Anyway, the script is running as we speak and I see what you mean; Im 30 minutes in and there's a 20C difference between the gantry and Y extrusion (and they were the same before I started).

Thanks!
