### ISSUE TITLE
Script is running but not making more bed meshes 

### ISSUE THREAD

**Issue by Hr46ph** [JiMcNulty/FDC#3]
Maybe its supposed to happen, but this is the latest output from the script, from like 30 minutes ago.

```
Measuring (#39)...Gantry/bed already trammed.      
Tramming gantry/bed...DONE
DONE
```

I think I noticed the last few meshes had longer pauses in between them (is that correct?) but now it seems to have stopped taking meshes entirely.

Any ideas please?

**Comment by JiMcNulty** [comment]
> Maybe its supposed to happen, but this is the latest output from the script, from like 30 minutes ago.
> 
> ```
> Tramming gantry/bed...DONE
> DONE```
> 
> I think I noticed the last few meshes had longer pauses in between them (is that correct?) but now it seems to have stopped taking meshes entirely.
> 
> Any ideas please?
> ```

Yes, it will only mesh when temperature raise by 0.2c at least
