### ISSUE TITLE
renaming first bed mesh

### ISSUE THREAD

**Issue by Hr46ph** [JiMcNulty/FDC#4]
Im at the point of copying the generated config and then it says this:
```
Paste if after the string ...-- SAVE_CONFIG --...
And after the default bed mesh
If you don't have one just copy your first bed mesh and change the name
```
I don't have one so I can copy the one `#*# [bed_mesh 31.3]`, which is the first one.

But what do rename it to? Just `[bed_mesh]` without a temperature, or some low ambient room temp?

Thanks! Can;t wait to try it out 😋

**Comment by JiMcNulty** [comment]
[bed_mesh default]
