### ISSUE TITLE
Edit macro with values printed when script is ran

### ISSUE THREAD

**Issue by Hr46ph** [JiMcNulty/FDC#5]
Point 11 [here](https://github.com/JiMcNulty/FDC/blob/main/README_EXTENDED.md#install-fdc-on-klipper) says to `Edit the macro with the min max temp, step and z_height_temps dictionary that was printed when you ran the script`.

The script on the Pi when starting the measurements, or processing the results on the local PC?

I checked both outputs from when I started them, but I don't really see which part I need to take?

The Pi started as follows:
```
pi@vcore-3:~/FDC $ nohup python3 measure_thermal_behavior.py 0.1 > out.txt &
tail -F out.txt
[1] 132124
nohup: ignoring input and redirecting stderr to stdout
Starting!
Homing...DONE
Gantry/bed already trammed.
Tramming gantry/bed...DONE
Setting heater targets: Bed=105.0 degC; Tool=255.0 degC
Parking toolhead at Z=240.0mm for bed heating...DONE
Waiting for bed to reach 105.0 degC...DONE
Heatsoaking bed for 0min...DONE                     
Starting!
```
And the local script to process did this:
```
Hr46ph@mylocalpc ~/fdc_meshes/FDC $ python3 generate_FDC_meshes_z_heights.py thermal_quant__2023-04-23_14-16-49.json 0.1 --filter_noise
Normalizing mesh 31.3 to middle zero, drift: 0.016875
Normalizing mesh 34.1 to middle zero, drift: 0.014062
Normalizing mesh 36.5 to middle zero, drift: 0.014375
Normalizing mesh 38.8 to middle zero, drift: 0.012812
```
Thanks! Almost there 😃

**Comment by JiMcNulty** [comment]
It will be at the end of the generate_FDC_meshes_z_heights.py, you will get popups for you to see the smoothing of the lines, after your close a window a new one will pop, 4 times

**Comment by Hr46ph** [comment]
I saved those graphs btw 😛 

Can I suggest you rewrite that point for clarity sake?

At point 3 [here](https://github.com/JiMcNulty/FDC/blob/main/README_EXTENDED.md#analyze-and-generate-the-deformation-data), you may want to add to read the output from the script. I followed the instructions, and didn't follow the output close enough to notice the line that says `Copy the vars above to the FDC macro, and don't forget to copy the new bed meshes!`.

Then at Point 11 [here](https://github.com/JiMcNulty/FDC/blob/main/README_EXTENDED.md#install-fdc-on-klipper), you could consider adding a reference to point 3 and name the variables by their literal names?

That would have helped me chase this one down.

Thanks.

**Comment by JiMcNulty** [comment]
Done
